// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF_TbGHcIGo3Xv2pSSYgFss3e-fycC1RQ',
    appId: '1:1023012900652:web:7ed262c71b22fb2d00a689',
    messagingSenderId: '1023012900652',
    projectId: 'forexcalculator-fc8a4',
    authDomain: 'forexcalculator-fc8a4.firebaseapp.com',
    storageBucket: 'forexcalculator-fc8a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfIYtvo8fX2szHC9IlfmSuHk0tCtUytPs',
    appId: '1:1023012900652:android:327d5752e12f3a4900a689',
    messagingSenderId: '1023012900652',
    projectId: 'forexcalculator-fc8a4',
    storageBucket: 'forexcalculator-fc8a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGzzmxehuBQje8jZ8HDSHZPLGQU1YmwEM',
    appId: '1:1023012900652:ios:7c9b956f72301f3800a689',
    messagingSenderId: '1023012900652',
    projectId: 'forexcalculator-fc8a4',
    storageBucket: 'forexcalculator-fc8a4.firebasestorage.app',
    iosBundleId: 'com.example.forexCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGzzmxehuBQje8jZ8HDSHZPLGQU1YmwEM',
    appId: '1:1023012900652:ios:7c9b956f72301f3800a689',
    messagingSenderId: '1023012900652',
    projectId: 'forexcalculator-fc8a4',
    storageBucket: 'forexcalculator-fc8a4.firebasestorage.app',
    iosBundleId: 'com.example.forexCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF_TbGHcIGo3Xv2pSSYgFss3e-fycC1RQ',
    appId: '1:1023012900652:web:1b65975aec6d703d00a689',
    messagingSenderId: '1023012900652',
    projectId: 'forexcalculator-fc8a4',
    authDomain: 'forexcalculator-fc8a4.firebaseapp.com',
    storageBucket: 'forexcalculator-fc8a4.firebasestorage.app',
  );
}
